package compiler

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"

	"gopkg.in/yaml.v3"
)

const Header = "<!-- Auto-generated by promptherder — do not edit -->\n"

type Options struct {
	Scope              string // repository (default) or user; user profiles currently Codex/Claude
	Targets            []string
	Include            []string
	Overrides          []string
	Skills             []string // nil selects all; explicit empty selects none
	CommandPrefix      string
	Strict             bool
	UpdateLock         bool
	Adopt              bool
	ProjectDocMaxBytes int
}

type Capability struct {
	Rules        string `json:"rules"`
	Skills       string `json:"skills"`
	Evidence     string `json:"evidence"`
	Verified     string `json:"verified"`
	NativePaths  bool   `json:"native_paths"`
	NativeManual bool   `json:"native_manual"`
}

// These are documented repository profiles, not promises about uninspected
// installations. Runtime tests and user/global settings are reported separately.
var Capabilities = map[string]Capability{
	"codex":       {"AGENTS.md", ".agents/skills", "https://learn.chatgpt.com/docs/build-skills", "2026-09-08", false, true},
	"claude":      {".claude/rules", ".claude/skills", "https://code.claude.com/docs/en/skills", "2026-09-08", true, true},
	"copilot":     {".github/instructions", ".github/skills", "https://code.visualstudio.com/docs/agent-customization/agent-skills", "2026-09-08", true, true},
	"cursor":      {".cursor/rules", ".agents/skills", "https://cursor.com/docs/rules", "2026-09-08", true, true},
	"windsurf":    {".windsurf/rules", ".windsurf/skills", "https://docs.devin.ai/desktop/cascade/skills", "2026-09-08", true, false},
	"cline":       {".clinerules", ".cline/skills", "https://docs.cline.bot/customization/skills", "2026-09-08", true, false},
	"antigravity": {".agents/rules", ".agents/skills", "https://antigravity.google/docs/skills/", "2026-09-08", true, false},
}

type Diagnostic struct {
	Severity string `json:"severity"`
	Code     string `json:"code"`
	Path     string `json:"path,omitempty"`
	Message  string `json:"message"`
}
type Artifact struct {
	Path    string      `json:"path"`
	Content []byte      `json:"-"`
	Mode    fs.FileMode `json:"mode"`
	Kind    string      `json:"kind"`
	ID      string      `json:"id"`
	Origins []string    `json:"origins"`
	Targets []string    `json:"targets"`
	Hash    string      `json:"hash"`
	Bytes   int         `json:"bytes"`
}
type Plan struct {
	Scope       string                `json:"scope"`
	Root        string                `json:"-"`
	Targets     []string              `json:"targets"`
	Artifacts   []Artifact            `json:"artifacts"`
	Delete      []string              `json:"delete"`
	Diagnostics []Diagnostic          `json:"diagnostics"`
	Locks       map[string]HerdLock   `json:"herds"`
	Profiles    map[string]Capability `json:"profiles"`
	Before      map[string]Snapshot   `json:"-"`
	Previous    Manifest              `json:"-"`
	opts        Options
}

func (p *Plan) note(severity, code, path, message string) {
	p.Diagnostics = append(p.Diagnostics, Diagnostic{severity, code, path, message})
}
func (p *Plan) HasErrors() bool {
	for _, d := range p.Diagnostics {
		if d.Severity == "error" {
			return true
		}
	}
	return false
}
func (p *Plan) add(a Artifact) {
	if a.Mode == 0 {
		a.Mode = 0644
	}
	a.Hash = digest(a.Content)
	a.Bytes = len(a.Content)
	for i := range p.Artifacts {
		old := &p.Artifacts[i]
		if old.Path == a.Path {
			if old.Hash != a.Hash || old.Mode != a.Mode {
				p.note("error", "output-conflict", a.Path, "enabled targets require different content at the same path; use portable content or separate checkouts")
				return
			}
			for _, t := range a.Targets {
				if !contains(old.Targets, t) {
					old.Targets = append(old.Targets, t)
				}
			}
			for _, o := range a.Origins {
				if !contains(old.Origins, o) {
					old.Origins = append(old.Origins, o)
				}
			}
			return
		}
	}
	p.Artifacts = append(p.Artifacts, a)
}

func Build(ctx context.Context, root string, opts Options) (*Plan, error) {
	if opts.Scope == "" {
		opts.Scope = "repository"
	}
	if opts.Scope != "repository" && opts.Scope != "user" {
		return nil, fmt.Errorf("unknown scope %q", opts.Scope)
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	p := &Plan{Scope: opts.Scope, Root: abs, Targets: append([]string{}, opts.Targets...), opts: opts, Before: map[string]Snapshot{}}
	sort.Strings(p.Targets)
	for i, t := range p.Targets {
		if opts.Scope == "user" && t != "codex" && t != "claude" {
			return nil, fmt.Errorf("user scope is currently verified only for codex and claude; %s requires repository scope", t)
		}
		if _, ok := Capabilities[t]; !ok {
			return nil, fmt.Errorf("unsupported target %q", t)
		}
		if i > 0 && p.Targets[i-1] == t {
			return nil, fmt.Errorf("duplicate target %s", t)
		}
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	p.Previous, err = readManifest(abs)
	if err != nil {
		return nil, err
	}
	if p.Previous.Version != 0 {
		previousScope := p.Previous.Scope
		if previousScope == "" {
			previousScope = "repository"
		}
		if previousScope != opts.Scope {
			return nil, fmt.Errorf("existing manifest belongs to %s scope, requested %s", previousScope, opts.Scope)
		}
	}
	c, err := loadContent(abs, opts, p.Previous)
	if err != nil {
		return nil, err
	}
	p.Profiles = map[string]Capability{}
	for _, t := range p.Targets {
		p.Profiles[t] = Capabilities[t]
	}
	p.Locks = c.Locks
	if err := p.verifyLock(); err != nil {
		return nil, err
	}
	shared := []string{}
	for _, t := range p.Targets {
		if t != "antigravity" && t != "windsurf" {
			shared = append(shared, t)
		}
	}
	baseline := Header
	origins := []string{}
	for _, r := range c.Rules {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if r.Activation == "always" {
			baseline += "\n" + strings.TrimSpace(r.Body) + "\n"
			origins = append(origins, r.Source.Origin)
		}
		for key := range r.Meta {
			if !contains([]string{"id", "activation", "trigger", "paths", "applyTo", "globs", "required", "description"}, key) {
				p.note("warning", "unknown-rule-metadata", r.Source.Origin, "untranslated field: "+key)
			}
		}
		for _, t := range p.Targets {
			if r.Activation == "always" && contains(shared, t) {
				continue
			}
			p.renderRule(r, t, &baseline)
		}
	}
	if len(shared) > 0 {
		path := "AGENTS.md"
		if opts.Scope == "user" {
			path = ".codex/AGENTS.md"
			if !contains(p.Targets, "codex") {
				path = ".claude/CLAUDE.md"
			}
		}
		p.add(Artifact{Path: path, Content: []byte(baseline), Kind: "baseline", ID: "baseline", Origins: origins, Targets: shared})
	}
	if contains(p.Targets, "claude") && (opts.Scope != "user" || contains(p.Targets, "codex")) {
		path, bridge := "CLAUDE.md", "@AGENTS.md"
		if opts.Scope == "user" {
			path, bridge = ".claude/CLAUDE.md", "@../.codex/AGENTS.md"
		}
		p.add(Artifact{Path: path, Content: []byte(Header + "\n" + bridge + "\n"), Kind: "bridge", ID: "claude-baseline", Origins: origins, Targets: []string{"claude"}})
	}
	selected := map[string]bool{}
	for _, id := range opts.Skills {
		selected[id] = true
	}
	// Compute dependency closure without recursion, including cyclic bundles.
	for changed := true; changed; {
		changed = false
		for _, s := range c.Skills {
			if opts.Skills != nil && !selected[s.ID] {
				continue
			}
			for _, dependency := range s.Requires {
				if !selected[dependency] {
					selected[dependency] = true
					changed = true
				}
			}
		}
	}
	for _, s := range c.Skills {
		if s.Workflow {
			s.Body = workflowAliases(c.Skills) + s.Body
		}
		if opts.Skills != nil && !selected[s.ID] {
			continue
		}
		for _, t := range p.Targets {
			if err := p.renderSkill(s, t); err != nil {
				return nil, err
			}
		}
	}
	for _, id := range opts.Skills {
		found := false
		for _, s := range c.Skills {
			found = found || s.ID == id
		}
		if !found {
			p.note("error", "missing-skill", id, "selected skill does not exist")
		}
	}
	p.checkDiscovery()
	if err := p.inspectExisting(); err != nil {
		return nil, err
	}
	// Adoption may add a user-owned prefix to the generated baseline.
	p.checkBudgets()
	for _, rel := range []string{".promptherder/manifest.json", ".promptherder/lock.json"} {
		s, err := snapshot(p.Root, rel)
		if err != nil {
			return nil, err
		}
		p.Before[rel] = s
	}
	if opts.Strict {
		for i := range p.Diagnostics {
			if p.Diagnostics[i].Severity == "warning" {
				p.Diagnostics[i].Severity = "error"
			}
		}
	}
	sort.Slice(p.Artifacts, func(i, j int) bool { return p.Artifacts[i].Path < p.Artifacts[j].Path })
	for i := range p.Artifacts {
		sort.Strings(p.Artifacts[i].Targets)
		sort.Strings(p.Artifacts[i].Origins)
	}
	sort.Strings(p.Delete)
	sort.Slice(p.Diagnostics, func(i, j int) bool {
		a, b := p.Diagnostics[i], p.Diagnostics[j]
		return a.Path+a.Code+a.Message < b.Path+b.Code+b.Message
	})
	return p, nil
}

func marshalDoc(meta map[string]any, body string) []byte {
	data, _ := yaml.Marshal(meta)
	return []byte("---\n" + string(data) + "---\n\n" + Header + "\n" + strings.TrimSpace(body) + "\n")
}
func safeID(id string) string { return strings.NewReplacer("/", "-", ".", "-").Replace(id) }

func (p *Plan) renderRule(r Rule, t string, baseline *string) {
	id := safeID(r.ID)
	meta := map[string]any{}
	path := ""
	body := r.Body
	if r.Activation == "manual" || r.Activation == "relevance" {
		d := r.Document
		d.Meta = map[string]any{"name": "rule-" + id, "description": str(r.Meta, "description")}
		if str(d.Meta, "description") == "" {
			d.Meta["description"] = "Apply " + r.ID + " guidance when explicitly requested."
		}
		s := Skill{ID: "rule-" + id, Document: d, Manual: r.Activation == "manual", Files: map[string]Source{}}
		if err := p.renderSkill(s, t); err != nil {
			p.note("error", "rule-skill", r.Source.Origin, err.Error())
		}
		return
	}
	switch t {
	case "codex":
		path = ".promptherder/references/rules/" + id + ".md"
		reference := path
		if p.Scope == "user" {
			reference = "../" + path
		}
		*baseline += fmt.Sprintf("\nWhen working on paths matching %s, read and follow [%s](%s).\n", strings.Join(r.Paths, ", "), r.ID, reference)
		severity := "warning"
		if r.Required {
			severity = "error"
		}
		p.note(severity, "model-mediated-paths", path, "Codex has no native arbitrary glob rule; emitted a conditional reference")
	case "claude":
		path = ".claude/rules/" + id + ".md"
		meta["paths"] = r.Paths
	case "copilot":
		path = ".github/instructions/" + id + ".instructions.md"
		meta["applyTo"] = strings.Join(r.Paths, ",")
	case "cursor":
		path = ".cursor/rules/" + id + ".mdc"
		meta["alwaysApply"] = false
		meta["globs"] = r.Paths
		meta["description"] = str(r.Meta, "description")
	case "cline":
		path = ".clinerules/" + id + ".md"
		meta["paths"] = r.Paths
	case "windsurf", "antigravity":
		path = Capabilities[t].Rules + "/" + id + ".md"
		meta["trigger"] = "always_on"
		if r.Activation == "paths" {
			meta["trigger"] = "glob"
			meta["globs"] = strings.Join(r.Paths, ",")
		}
	}
	data := []byte(Header + "\n" + body)
	if len(meta) > 0 {
		data = marshalDoc(meta, body)
	}
	p.add(Artifact{Path: path, Content: data, Kind: "rule", ID: r.ID, Origins: []string{r.Source.Origin}, Targets: []string{t}})
}

func (p *Plan) skillRoot(t string) string {
	if t == "copilot" {
		if contains(p.Targets, "codex") || contains(p.Targets, "cursor") || contains(p.Targets, "antigravity") {
			return ".agents/skills"
		}
		if contains(p.Targets, "claude") {
			return ".claude/skills"
		}
	}
	if t == "cline" && contains(p.Targets, "claude") {
		return ".claude/skills"
	}
	return Capabilities[t].Skills
}

func (p *Plan) renderSkill(s Skill, t string) error {
	d := s.Document
	if v, ok := s.Variants[t]; ok {
		d = v
	}
	meta := map[string]any{}
	for k, v := range d.Meta {
		meta[k] = v
	}
	meta["name"] = s.ID
	manual := s.Manual
	if explicit, ok := meta["disable-model-invocation"].(bool); ok {
		manual = explicit
	}
	if str(meta, "description") == "" {
		return fmt.Errorf("%s: skill variant needs description", d.Source.Origin)
	}
	if manual {
		meta["disable-model-invocation"] = true
		if !Capabilities[t].NativeManual {
			p.note("warning", "manual-fallback", s.ID, "manual-only loading not verified for "+t+"; requires explicit invocation guidance")
		}
	}
	// Standard metadata is portable. Execution/permission extensions must be
	// explicitly authored for their host rather than leaking through shared bundles.
	for k := range meta {
		if contains([]string{"name", "description", "license", "compatibility", "metadata", "disable-model-invocation", "user-invocable"}, k) {
			continue
		}
		if _, variant := s.Variants[t]; !variant {
			p.note("warning", "host-metadata", d.Source.Origin, "field "+k+" is retained; verify its behavior for "+t)
		}
	}
	body := d.Body
	if s.Workflow {
		body = "This is an explicitly requested workflow. Apply these instructions only while this workflow is active; after completing it, follow the next user request. Workflow text does not grant permission for unrelated actions.\n\n" + body
	}
	if manual {
		body = "Use this procedure only when the user explicitly requests it.\n\n" + body
	}
	root := p.skillRoot(t) + "/" + s.ID
	p.add(Artifact{Path: root + "/SKILL.md", Content: marshalDoc(meta, body), Kind: "skill", ID: s.ID, Origins: []string{d.Source.Origin}, Targets: []string{t}})
	for _, rel := range keys(s.Files) {
		if t == "codex" && manual && rel == "agents/openai.yaml" {
			continue
		}
		src := s.Files[rel]
		p.add(Artifact{Path: root + "/" + rel, Content: src.Data, Mode: src.Mode, Kind: "resource", ID: s.ID, Origins: []string{src.Origin}, Targets: []string{t}})
	}
	if t == "codex" && manual {
		config := map[string]any{}
		if src, ok := s.Files["agents/openai.yaml"]; ok {
			if err := yaml.Unmarshal(src.Data, &config); err != nil {
				return fmt.Errorf("%s: %w", src.Origin, err)
			}
		}
		if config == nil {
			config = map[string]any{}
		}
		policy, ok := config["policy"].(map[string]any)
		if !ok {
			policy = map[string]any{}
		}
		policy["allow_implicit_invocation"] = false
		config["policy"] = policy
		data, err := yaml.Marshal(config)
		if err != nil {
			return err
		}
		p.add(Artifact{Path: root + "/agents/openai.yaml", Content: data, Kind: "resource", ID: s.ID, Origins: []string{d.Source.Origin}, Targets: []string{t}})
	}
	return nil
}

func visible(host, path string) bool {
	roots := []string{Capabilities[host].Skills}
	switch host {
	case "copilot":
		roots = append(roots, ".agents/skills", ".claude/skills")
	case "cursor":
		roots = append(roots, ".cursor/skills")
	case "cline":
		roots = append(roots, ".claude/skills", ".clinerules/skills")
	}
	for _, r := range roots {
		if strings.HasPrefix(path, r+"/") {
			return true
		}
	}
	return false
}

func (p *Plan) checkDiscovery() {
	for _, host := range p.Targets {
		seen := map[string]Artifact{}
		for _, a := range p.Artifacts {
			if a.Kind != "skill" || !visible(host, a.Path) {
				continue
			}
			if old, ok := seen[a.ID]; ok {
				severity, code := "warning", "duplicate-discovery"
				if old.Hash != a.Hash {
					severity, code = "error", "variant-leak"
				}
				p.note(severity, code, a.Path, fmt.Sprintf("%s also discovers %s for %s", host, old.Path, a.ID))
			} else {
				seen[a.ID] = a
			}
		}
	}
}

func (p *Plan) checkBudgets() {
	limit := p.opts.ProjectDocMaxBytes
	if limit == 0 {
		limit = 32768
	}
	for _, a := range p.Artifacts {
		if a.Kind == "baseline" {
			if contains(p.Targets, "codex") && a.Bytes > limit {
				p.note("error", "project-budget", a.Path, fmt.Sprintf("%d bytes exceeds configured project budget %d", a.Bytes, limit))
			} else if a.Bytes > 8192 {
				p.note("warning", "baseline-size", a.Path, "baseline exceeds the 8 KiB quality target")
			}
		}
		if a.Kind == "skill" && a.Bytes > 20000 {
			p.note("warning", "skill-size", a.Path, "skill body is large; move examples/checklists to references (byte heuristic, not token count)")
		}
		if a.Kind == "rule" && (strings.HasPrefix(a.Path, ".windsurf/") || strings.HasPrefix(a.Path, ".agents/rules/")) && utf8.RuneCount(a.Content) > 12000 {
			p.note("error", "rule-budget", a.Path, "rule exceeds 12,000 characters")
		}
	}
}

func (p *Plan) Print(w io.Writer, explain string) {
	for _, a := range p.Artifacts {
		if explain != "" && a.ID != explain {
			continue
		}
		fmt.Fprintf(w, "%s %s (%d bytes; %s) <- %s\n", a.Kind, a.Path, a.Bytes, strings.Join(a.Targets, ","), strings.Join(a.Origins, ", "))
	}
	for _, path := range p.Delete {
		fmt.Fprintf(w, "remove %s\n", path)
	}
	for _, d := range p.Diagnostics {
		fmt.Fprintf(w, "%s [%s] %s: %s\n", d.Severity, d.Code, d.Path, d.Message)
	}
	fmt.Fprintln(w, "Discovery is based on documented repository profiles. Global settings, host versions, and model adherence require runtime verification.")
}

func (p *Plan) verifyLock() error {
	data, err := os.ReadFile(filepath.Join(p.Root, ".promptherder/lock.json"))
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	var locked map[string]HerdLock
	if err := json.Unmarshal(data, &locked); err != nil {
		return fmt.Errorf("invalid lockfile: %w", err)
	}
	if !p.opts.UpdateLock {
		for name := range locked {
			if _, ok := p.Locks[name]; !ok {
				p.note("error", "lock-mismatch", name, "locked herd is missing; restore it or review removal with --update-lock")
			}
		}
		for name, lock := range p.Locks {
			if old, ok := locked[name]; ok && old != lock {
				p.note("error", "lock-mismatch", name, "herd content changed; review it and use --update-lock")
			}
		}
	}
	return nil
}
