package app

import (
	"context"
	"path/filepath"
)

const claudeTarget = "CLAUDE.md"

// ClaudeTarget implements the Target interface for Claude Code.
// It writes a single CLAUDE.md at the repo root containing all rules,
// skills, and workflows.
type ClaudeTarget struct {
	SourceDir string
	Include   []string
}

func (t ClaudeTarget) Name() string { return "claude" }

func (t ClaudeTarget) Install(ctx context.Context, cfg TargetConfig) ([]string, error) {
	srcDir := t.SourceDir
	if srcDir == "" {
		srcDir = defaultSourceDir
	}

	header := "<!-- Auto-generated by promptherder — do not edit -->\n"
	content, names, err := buildFullConcatTarget(cfg.RepoPath, srcDir, t.Include, header, "claude")
	if err != nil {
		return nil, err
	}
	if content == nil {
		cfg.Logger.Debug("no source files found", "target", "claude")
		return nil, nil
	}

	targetPath := filepath.Join(cfg.RepoPath, claudeTarget)
	targetRel := claudeTarget

	if cfg.DryRun {
		cfg.Logger.Info("dry-run", "target", targetRel, "sources", names)
	} else {
		if err := writeFile(targetPath, content); err != nil {
			return nil, err
		}
		cfg.Logger.Info("synced", "target", targetRel, "sources", names)
	}

	return []string{targetRel}, nil
}
