package app

import (
	"context"
	"path/filepath"
)

const clineTargetDir = ".clinerules"
const clineTargetFile = "promptherder.md"

// ClineTarget implements the Target interface for Cline.
// It writes a single .clinerules/promptherder.md containing all rules,
// skills, and workflows.
type ClineTarget struct {
	SourceDir string
	Include   []string
}

func (t ClineTarget) Name() string { return "cline" }

func (t ClineTarget) Install(ctx context.Context, cfg TargetConfig) ([]string, error) {
	srcDir := t.SourceDir
	if srcDir == "" {
		srcDir = defaultSourceDir
	}

	header := "<!-- Auto-generated by promptherder — do not edit -->\n"
	content, names, err := buildFullConcatTarget(cfg.RepoPath, srcDir, t.Include, header, "cline")
	if err != nil {
		return nil, err
	}
	if content == nil {
		cfg.Logger.Debug("no source files found", "target", "cline")
		return nil, nil
	}

	targetRel := filepath.ToSlash(filepath.Join(clineTargetDir, clineTargetFile))
	targetPath := filepath.Join(cfg.RepoPath, clineTargetDir, clineTargetFile)

	if cfg.DryRun {
		cfg.Logger.Info("dry-run", "target", targetRel, "sources", names)
	} else {
		if err := writeFile(targetPath, content); err != nil {
			return nil, err
		}
		cfg.Logger.Info("synced", "target", targetRel, "sources", names)
	}

	return []string{targetRel}, nil
}
