package app

import (
	"context"
	"path/filepath"
)

const codexTarget = "AGENTS.md"

// CodexTarget implements the Target interface for OpenAI Codex.
// It writes a single AGENTS.md at the repo root containing all rules,
// skills, and workflows.
type CodexTarget struct {
	SourceDir string
	Include   []string
}

func (t CodexTarget) Name() string { return "codex" }

func (t CodexTarget) Install(ctx context.Context, cfg TargetConfig) ([]string, error) {
	srcDir := t.SourceDir
	if srcDir == "" {
		srcDir = defaultSourceDir
	}

	header := "<!-- Auto-generated by promptherder — do not edit -->\n"
	content, names, err := buildFullConcatTarget(cfg.RepoPath, srcDir, t.Include, header, "codex")
	if err != nil {
		return nil, err
	}
	if content == nil {
		cfg.Logger.Debug("no source files found", "target", "codex")
		return nil, nil
	}

	targetPath := filepath.Join(cfg.RepoPath, codexTarget)
	targetRel := codexTarget

	if cfg.DryRun {
		cfg.Logger.Info("dry-run", "target", targetRel, "sources", names)
	} else {
		if err := writeFile(targetPath, content); err != nil {
			return nil, err
		}
		cfg.Logger.Info("synced", "target", targetRel, "sources", names)
	}

	return []string{targetRel}, nil
}
