package app

import (
	"context"
	"path/filepath"
)

const cursorTargetDir = ".cursor/rules"
const cursorTargetFile = "promptherder.md"

// CursorTarget implements the Target interface for Cursor AI.
// It writes a single .cursor/rules/promptherder.md containing all rules,
// skills, and workflows.
type CursorTarget struct {
	SourceDir string
	Include   []string
}

func (t CursorTarget) Name() string { return "cursor" }

func (t CursorTarget) Install(ctx context.Context, cfg TargetConfig) ([]string, error) {
	srcDir := t.SourceDir
	if srcDir == "" {
		srcDir = defaultSourceDir
	}

	header := "<!-- Auto-generated by promptherder — do not edit -->\n"
	content, names, err := buildFullConcatTarget(cfg.RepoPath, srcDir, t.Include, header, "cursor")
	if err != nil {
		return nil, err
	}
	if content == nil {
		cfg.Logger.Debug("no source files found", "target", "cursor")
		return nil, nil
	}

	targetRel := filepath.ToSlash(filepath.Join(cursorTargetDir, cursorTargetFile))
	targetPath := filepath.Join(cfg.RepoPath, cursorTargetDir, cursorTargetFile)

	if cfg.DryRun {
		cfg.Logger.Info("dry-run", "target", targetRel, "sources", names)
	} else {
		if err := writeFile(targetPath, content); err != nil {
			return nil, err
		}
		cfg.Logger.Info("synced", "target", targetRel, "sources", names)
	}

	return []string{targetRel}, nil
}
