package app

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSimpleConcatTarget_AllPaths(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		target     SimpleConcatTarget
		outputPath string
	}{
		{"claude", NewClaudeTarget(nil), "CLAUDE.md"},
		{"codex", NewCodexTarget(nil), "AGENTS.md"},
		{"cursor", NewCursorTarget(nil), ".cursor/rules/promptherder.md"},
		{"windsurf", NewWindsurfTarget(nil), ".windsurf/rules/promptherder.md"},
		{"cline", NewClineTarget(nil), ".clinerules/promptherder.md"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()

			srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
			mustMkdir(t, srcDir)
			mustWrite(t, filepath.Join(srcDir, "test.md"), "# Test Rule\n")

			if tt.target.Name() != tt.name {
				t.Errorf("expected name %q, got %q", tt.name, tt.target.Name())
			}

			installed, err := tt.target.Install(context.Background(), TargetConfig{
				RepoPath: dir,
				Logger:   testLogger(t),
			})
			if err != nil {
				t.Fatal(err)
			}

			if len(installed) != 1 || installed[0] != tt.outputPath {
				t.Errorf("expected [%s], got %v", tt.outputPath, installed)
			}

			absPath := filepath.Join(dir, filepath.FromSlash(tt.outputPath))
			data, err := os.ReadFile(absPath)
			if err != nil {
				t.Fatalf("output file should exist at %s: %v", tt.outputPath, err)
			}

			s := string(data)
			if !strings.Contains(s, "Auto-generated by promptherder") {
				t.Error("expected auto-generated header")
			}
			if !strings.Contains(s, "# Test Rule") {
				t.Error("expected rule content")
			}
		})
	}
}

func TestSimpleConcatTarget_DryRun(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test.md"), "# Rule\n")

	target := NewClaudeTarget(nil)
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		DryRun:   true,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}

	if len(installed) != 1 {
		t.Errorf("expected 1 installed path in dry-run, got %d", len(installed))
	}

	// File should NOT exist in dry-run.
	if _, err := os.Stat(filepath.Join(dir, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Error("CLAUDE.md should not exist in dry-run")
	}
}

func TestSimpleConcatTarget_NoSources(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	target := NewClaudeTarget(nil)
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}
	if installed != nil {
		t.Errorf("expected nil installed, got %v", installed)
	}
}

func TestSimpleConcatTarget_ContextCancellation(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test.md"), "# Rule\n")

	ctx, cancel := context.WithCancel(context.Background())
	cancel() // Cancel immediately.

	target := NewClaudeTarget(nil)
	_, err := target.Install(ctx, TargetConfig{
		RepoPath: dir,
		Logger:   testLogger(t),
	})
	if err == nil {
		t.Error("expected context cancellation error")
	}
}

func TestSimpleConcatTarget_SkipsForeignFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test.md"), "# Rule\n")

	// Pre-create a foreign CLAUDE.md (no promptherder header).
	mustWrite(t, filepath.Join(dir, "CLAUDE.md"), "# My hand-written Claude instructions\n\nDo not overwrite me.\n")

	target := NewClaudeTarget(nil)
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}

	// Should skip — nil result, no error.
	if installed != nil {
		t.Errorf("expected nil installed for foreign file, got %v", installed)
	}

	// Original content should be preserved.
	data, err := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "Do not overwrite me") {
		t.Error("foreign file content was destroyed")
	}
}

func TestSimpleConcatTarget_OverwritesOwnFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test.md"), "# Updated Rule\n")

	// Pre-create a promptherder-generated CLAUDE.md (has our header).
	mustWrite(t, filepath.Join(dir, "CLAUDE.md"), "<!-- Auto-generated by promptherder — do not edit -->\n\n# Old Rule\n")

	target := NewClaudeTarget(nil)
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}

	if len(installed) != 1 {
		t.Fatalf("expected 1 installed, got %d", len(installed))
	}

	// Content should be updated.
	data, err := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "# Updated Rule") {
		t.Error("own file should have been overwritten with new content")
	}
}
