package app

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClaudeTarget_WritesCLAUDEMD(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	// Create source rules.
	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test-rule.md"), "# Test Rule\nHello.\n")

	target := ClaudeTarget{}
	cfg := TargetConfig{
		RepoPath: dir,
		DryRun:   false,
		Logger:   testLogger(t),
	}

	installed, err := target.Install(context.Background(), cfg)
	if err != nil {
		t.Fatal(err)
	}

	if len(installed) != 1 || installed[0] != "CLAUDE.md" {
		t.Errorf("expected [CLAUDE.md], got %v", installed)
	}

	data, err := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}

	s := string(data)
	if !strings.Contains(s, "Auto-generated by promptherder") {
		t.Error("expected auto-generated header")
	}
	if !strings.Contains(s, "# Test Rule") {
		t.Error("expected rule content")
	}
}

func TestCodexTarget_WritesAGENTSMD(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test.md"), "# Codex Rule\n")

	target := CodexTarget{}
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}

	if len(installed) != 1 || installed[0] != "AGENTS.md" {
		t.Errorf("expected [AGENTS.md], got %v", installed)
	}

	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); err != nil {
		t.Errorf("AGENTS.md should exist: %v", err)
	}
}

func TestCursorTarget_WritesToCorrectPath(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test.md"), "# Cursor Rule\n")

	target := CursorTarget{}
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}

	expected := ".cursor/rules/promptherder.md"
	if len(installed) != 1 || installed[0] != expected {
		t.Errorf("expected [%s], got %v", expected, installed)
	}

	if _, err := os.Stat(filepath.Join(dir, ".cursor", "rules", "promptherder.md")); err != nil {
		t.Errorf("cursor target file should exist: %v", err)
	}
}

func TestWindsurfTarget_WritesToCorrectPath(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test.md"), "# Windsurf Rule\n")

	target := WindsurfTarget{}
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}

	expected := ".windsurf/rules/promptherder.md"
	if len(installed) != 1 || installed[0] != expected {
		t.Errorf("expected [%s], got %v", expected, installed)
	}
}

func TestClineTarget_WritesToCorrectPath(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test.md"), "# Cline Rule\n")

	target := ClineTarget{}
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}

	expected := ".clinerules/promptherder.md"
	if len(installed) != 1 || installed[0] != expected {
		t.Errorf("expected [%s], got %v", expected, installed)
	}
}

func TestClaudeTarget_DryRun(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	srcDir := filepath.Join(dir, ".promptherder", "agent", "rules")
	mustMkdir(t, srcDir)
	mustWrite(t, filepath.Join(srcDir, "test.md"), "# Rule\n")

	target := ClaudeTarget{}
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		DryRun:   true,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}

	if len(installed) != 1 {
		t.Errorf("expected 1 installed path in dry-run, got %d", len(installed))
	}

	// File should NOT exist in dry-run.
	if _, err := os.Stat(filepath.Join(dir, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Error("CLAUDE.md should not exist in dry-run")
	}
}

func TestClaudeTarget_NoSources(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	target := ClaudeTarget{}
	installed, err := target.Install(context.Background(), TargetConfig{
		RepoPath: dir,
		Logger:   testLogger(t),
	})
	if err != nil {
		t.Fatal(err)
	}
	if installed != nil {
		t.Errorf("expected nil installed, got %v", installed)
	}
}
