package app

import (
	"context"
	"path/filepath"
)

// SimpleConcatTarget implements Target for agents that use a single concatenated
// markdown file (Claude Code, Codex, Cursor, Windsurf, Cline).
type SimpleConcatTarget struct {
	TargetName  string   // e.g. "claude"
	OutputPath  string   // e.g. "CLAUDE.md" or ".cursor/rules/promptherder.md"
	VariantName string   // e.g. "claude" — used to select skill variants
	Include     []string // glob patterns for source files
}

func (t SimpleConcatTarget) Name() string { return t.TargetName }

func (t SimpleConcatTarget) Install(ctx context.Context, cfg TargetConfig) ([]string, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}

	header := "<!-- Auto-generated by promptherder — do not edit -->\n"
	content, names, err := buildFullConcatTarget(ctx, cfg.RepoPath, defaultSourceDir, t.Include, header, t.VariantName)
	if err != nil {
		return nil, err
	}
	if content == nil {
		cfg.Logger.Debug("no source files found", "target", t.TargetName)
		return nil, nil
	}

	targetPath := filepath.Join(cfg.RepoPath, filepath.FromSlash(t.OutputPath))
	targetRel := filepath.ToSlash(t.OutputPath)

	if cfg.DryRun {
		cfg.Logger.Info("dry-run", "target", targetRel, "sources", names)
	} else {
		if err := writeFile(targetPath, content); err != nil {
			return nil, err
		}
		cfg.Logger.Info("synced", "target", targetRel, "sources", names)
	}

	return []string{targetRel}, nil
}

// NewClaudeTarget creates a target for Claude Code (CLAUDE.md).
func NewClaudeTarget(include []string) SimpleConcatTarget {
	return SimpleConcatTarget{
		TargetName:  "claude",
		OutputPath:  "CLAUDE.md",
		VariantName: "claude",
		Include:     include,
	}
}

// NewCodexTarget creates a target for OpenAI Codex (AGENTS.md).
func NewCodexTarget(include []string) SimpleConcatTarget {
	return SimpleConcatTarget{
		TargetName:  "codex",
		OutputPath:  "AGENTS.md",
		VariantName: "codex",
		Include:     include,
	}
}

// NewCursorTarget creates a target for Cursor (.cursor/rules/promptherder.md).
func NewCursorTarget(include []string) SimpleConcatTarget {
	return SimpleConcatTarget{
		TargetName:  "cursor",
		OutputPath:  ".cursor/rules/promptherder.md",
		VariantName: "cursor",
		Include:     include,
	}
}

// NewWindsurfTarget creates a target for Windsurf (.windsurf/rules/promptherder.md).
func NewWindsurfTarget(include []string) SimpleConcatTarget {
	return SimpleConcatTarget{
		TargetName:  "windsurf",
		OutputPath:  ".windsurf/rules/promptherder.md",
		VariantName: "windsurf",
		Include:     include,
	}
}

// NewClineTarget creates a target for Cline (.clinerules/promptherder.md).
func NewClineTarget(include []string) SimpleConcatTarget {
	return SimpleConcatTarget{
		TargetName:  "cline",
		OutputPath:  ".clinerules/promptherder.md",
		VariantName: "cline",
		Include:     include,
	}
}
