package app

import (
	"context"
	"path/filepath"
)

const windsurfTargetDir = ".windsurf/rules"
const windsurfTargetFile = "promptherder.md"

// WindsurfTarget implements the Target interface for Windsurf AI.
// It writes a single .windsurf/rules/promptherder.md containing all rules,
// skills, and workflows.
type WindsurfTarget struct {
	SourceDir string
	Include   []string
}

func (t WindsurfTarget) Name() string { return "windsurf" }

func (t WindsurfTarget) Install(ctx context.Context, cfg TargetConfig) ([]string, error) {
	srcDir := t.SourceDir
	if srcDir == "" {
		srcDir = defaultSourceDir
	}

	header := "<!-- Auto-generated by promptherder — do not edit -->\n"
	content, names, err := buildFullConcatTarget(cfg.RepoPath, srcDir, t.Include, header, "windsurf")
	if err != nil {
		return nil, err
	}
	if content == nil {
		cfg.Logger.Debug("no source files found", "target", "windsurf")
		return nil, nil
	}

	targetRel := filepath.ToSlash(filepath.Join(windsurfTargetDir, windsurfTargetFile))
	targetPath := filepath.Join(cfg.RepoPath, windsurfTargetDir, windsurfTargetFile)

	if cfg.DryRun {
		cfg.Logger.Info("dry-run", "target", targetRel, "sources", names)
	} else {
		if err := writeFile(targetPath, content); err != nil {
			return nil, err
		}
		cfg.Logger.Info("synced", "target", targetRel, "sources", names)
	}

	return []string{targetRel}, nil
}
